version: "3"
services:
  react-app:
    build: ./metrics_plotter
    volumes:
      - ./metrics_plotter:/metrics_plotter:cached
    ports: 
      - "3000:3000"
    env_file:
        - ./metrics_plotter/.env
    networks:
      - dex-app
    depends_on:
      - api-server
  api-server:
    build: ./service_provider
    ports:
      - "5505:5505"
    volumes:
      - ./service_provider:/service_provider:cached
    env_file:
        - ./service_provider/.env
    networks:
      - dex-app
    depends_on:
      - mongo
      - metrics-reader
  metrics-reader:
    build: ./metrics_reader
    volumes:
      - ./metrics_reader:/metrics_reader:cached
    env_file:
        - ./metrics_reader/.env
    networks:
      - dex-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - dex-app
    volumes:
      - mongo-data:/data/db
networks:
  dex-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local