version: "3"
services:
  react-app:
    build: ./metrics_plotter
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVICE_PROVIDER_API_KEY=74fecf8a-c86e-4d30-936c-389cfbe951f5
      - REACT_APP_SERVICE_PROVIDER_URL=http://localhost:5505
    networks:
      - dex-app
    depends_on:
      - api-server
  api-server:
    build: ./service_provider
    ports:
      - "5505:5505"
    environment:
      - NODE_ENV=production
      - MONGO_DB_URL=mongodb://mongo:27017/dex_lectures
      - API_KEY=74fecf8a-c86e-4d30-936c-389cfbe951f5
      - API_PORT=5505
    networks:
      - dex-app
    depends_on:
      - mongo
      - metrics-reader
  metrics-reader:
    build: ./metrics_reader
    environment:
      - ENVIRONMENT=production
      - DEX_API_URL=https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
      - MONGO_DB_URL=mongo:27017
      - PAIRS=["0xbc9d21652cca70f54351e3fb982c6b5dbe992a22", "0xb4e16d0168e52d35cacd2c6185b44281ec28c9dc"]
    networks:
      - dex-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - dex-app
    volumes:
      - mongo-data:/data/db
networks:
  dex-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local